Repository skku-npc/sources, pull requests merged in 2020-10, with the labels that each got.

#18 Kosaraju
  kosaraju.cpp
Labels: Graph

#33 Extended Euclidean Algorithm
  extented_euclidean.cpp
Labels: Math

#35 Rearrange Directory
  data structure/fenwick.cpp
  data structure/hld.cpp
  data structure/merge_sort_tree.cpp
  data structure/ordered_set.cpp
  data structure/persistent_segment_tree.cpp
  data structure/segment_tree.cpp
  dp/convexhull_trick.cpp
  flow/dinic.cpp
  flow/hopcroft_karp.cpp
  flow/mcmf.cpp
  geometry/ccw.cpp
  geometry/rotating_calipers.cpp
  graph/kosaraju.cpp
  graph/tarjan.cpp
  math/2-sat.cpp
  math/euler_phi.cpp
  math/extented_euclidean.cpp
  math/fft.cpp
  math/math.cpp
  string/kmp.cpp
  string/manacher.cpp
  string/suffix_array.cpp
  string/trie.cpp
Labels: enhancement
